import type { ConfiguratorSchema } from '@/components/organisms/ConfiguratorForm/schema'

export const TIER_DEFAULTS: Record<string, Partial<ConfiguratorSchema>> = {
  launch: {
    tier: 'launch',
    name: '',
    locales: ['en'],
    defaultLocale: 'en',
    allowDarkMode: false,
    layoutWidth: 'w-[95%] md:w-9/10 max-w-layout-lg',
    selectedNavigation: 'nav-simple',
    selectedFooter: 'footer-simple',
    allowPostsCollection: false,
    allowOurTeamCollection: false,
    isSinglePage: true,
    crmProvider: 'none',
  },
  growth: {
    tier: 'growth',
    name: '',
    locales: ['en', 'es'],
    defaultLocale: 'en',
    allowDarkMode: true,
    layoutWidth: 'w-[95%] md:w-9/10 max-w-layout-lg',
    selectedNavigation: 'nav-mega',
    selectedFooter: 'footer-simple',
    allowPostsCollection: false,
    allowOurTeamCollection: true,
    isSinglePage: false,
    crmProvider: 'none',
  },
  scale: {
    tier: 'scale',
    name: '',
    locales: ['en', 'es', 'pt'],
    defaultLocale: 'en',
    allowDarkMode: true,
    selectedNavigation: 'nav-mega',
    selectedFooter: 'footer-mega',
    allowPostsCollection: true,
    allowOurTeamCollection: true,
    isSinglePage: false,
    crmProvider: 'none',
  },
  custom: {
    tier: 'custom',
    name: '',
    locales: ['en', 'es'],
    defaultLocale: 'en',
    allowDarkMode: false,
    layoutWidth: 'w-[95%] md:w-9/10 max-w-layout-lg',
    selectedNavigation: 'nav-simple',
    selectedFooter: 'footer-simple',
    allowPostsCollection: false,
    allowOurTeamCollection: false,
    isSinglePage: false,
    crmProvider: 'none',
  },
}
